name: cat-dog-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - tensorflow
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - ipykernel
  - pip
  - pip:
      - opencv-python
